// Wails v2 runtime — auto-generated by `wails dev` / `wails build`.
// This stub is replaced at build time; do not hand-edit.
'use strict';
export function WindowSetTitle(title) { window['wails']['SetTitle'](title); }
export function WindowFullscreen() { window['wails']['Fullscreen'](); }
export function WindowUnfullscreen() { window['wails']['UnFullscreen'](); }
export function BrowserOpenURL(url) { window['wails']['BrowserOpenURL'](url); }
export function EventsOn(event, callback) { return window['wails']['Events']['On'](event, callback); }
export function EventsOff(event, ...callbacks) { window['wails']['Events']['Off'](event, ...callbacks); }
export function EventsEmit(event, ...data) { window['wails']['Events']['Emit'](event, ...data); }
